name: Update Template Repo

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 5 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: "!contains(github.event.head_commit.message, '[nodoc]')"
    steps:
    - uses: actions/checkout@v2
      with:
        repository: "Ruby-Starter-Kits/Docker-Middleman-Template"
        path: App
        persist-credentials: false
    - uses: actions/checkout@v2
      with:
        repository: 'Ruby-Starter-Kits/Docker-Middleman-Generator'
        path: Docker-Middleman-Generator
        persist-credentials: false
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler: none
    - uses: actions/cache@v2.1.4
      with:
        path: ${{ github.workspace }}/vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - uses: actions/cache@v2.1.4
      with:
        path: ${{ github.workspace }}/App/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-
    - name: Build Environment
      run: |
        cd $GITHUB_WORKSPACE/App
        bundle config path $GITHUB_WORKSPACE/vendor/bundle
        gem install middleman
    - name: Clear previous build
      run: |
        cd $GITHUB_WORKSPACE/App
        shopt -s extglob
        rm -rfv !(".git"|"."|".."|"node_modules")
    - name: Build latest version of middleman
      run: |
        cd $GITHUB_WORKSPACE/App
        middleman init .
    - name: Copy docker files
      run: |
        cd $GITHUB_WORKSPACE/App
        rsync -a $GITHUB_WORKSPACE/Docker-Middleman-Generator/App-Template/ $GITHUB_WORKSPACE/App/
    - name: Pull docker image
      run: |
        cd $GITHUB_WORKSPACE/App
        docker-compose pull
    - uses: satackey/action-docker-layer-caching@v0
    - name: Test we can build docker
      run: |
        cd $GITHUB_WORKSPACE/App
        docker-compose build
    - name: Commit any new files
      run: |
        cd $GITHUB_WORKSPACE/Docker-Middleman-Generator
        DOCKER_MIDDLEMAN_GENERATOR_VERSION="Generator 0.1.0"
        MIDDLEMAN_VERSION=`gem list | grep 'middleman ('`

        cd $GITHUB_WORKSPACE/App
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -am "$MIDDLEMAN_VERSION | $DOCKER_MIDDLEMAN_GENERATOR_VERSION" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.LOCAL_GIT_TOKEN }}
        repository: 'Ruby-Starter-Kits/Docker-Middleman-Template'
        directory: App
        branch: ${{ github.ref }}
